---
# Placeholder for now as the Jenkins Master is running inside a docker container.
- name: copy service and timer file
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0644
  with_items:
    - jenkins-docker.service
    - override.conf
