---
# Role to setup Jenkins running as daemon
- hosts: localhost
  vars_files:
    - ../vars/ldap.yml
  environment:
    LDAP_PASSWORD: "{{ VAULT_LDAP_PASSWORD }}"

  tasks:
    - name: Create jenkins-pf.service.d directory in path /etc/systemd/system/ if it doesn't exist.
      file:
        path: /etc/systemd/system/jenkins-pf.service.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy jenkins-docker.service file /etc/systemd/system/ directory.
      copy:
        src: jenkins-pf.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
    
    - name: Template a override.j2 to /etc/systemd/system/jenkins-pd.service.d directory.
      template:
        src: override.j2
        dest: /etc/systemd/system/jenkins-pd.service.d/override.conf
        owner: root
        group: root
        mode: 0640