---
driver:
  name: docker
  use_sudo: false
  use_internal_docker_network: true

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: true
  require_ruby_for_busser: false

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    verifier:
      patterns:
        - test/integration/default/serverspec/default_spec.rb
