#!/usr/bin/env groovy
@Library(['global-pipeline-shared-libs@master','paas-pipeline-shared-libs@master']) _
pipeline {
  agent { node { label 'ec2' } }
  options {
    buildDiscarder(logRotator(numToKeepStr: '30'))
  }
  stages {
    stage('Do not build if skip-build is in commit message') {
      steps {
        setBuildDisplayName()
        skipOrNotSkip()
      }
    }
    stage('Kitchen Test') {
      when {
        environment name: 'SKIP', value: 'false'
      }
      steps {
        sh 'make test'
      }
    }
  }
  post {
    always {
      slackNotification(currentBuild.result, 'paas-jenkins')
      cleanWs()
    }
  }
}
